# This file was largely generated by Gemini 3.8 Flash, reviewed by @dubiouscandle.

import numpy as np
import pandas as pd
import plotly.graph_objects as go

# 1. Load and prepare combined data
df = pd.read_csv("stat_data_cleaned")
pred_combined = pd.concat([df["w_pred"], df["b_pred"]], ignore_index=True)
true_combined = pd.concat([df["w_true"], df["b_true"]], ignore_index=True)

# Filter 1% global extreme error tail
sq_errors = (pred_combined - true_combined) ** 2
cutoff = np.quantile(sq_errors, 0.99)
is_inlier = sq_errors <= cutoff

eval_df = pd.DataFrame(
    {"true": true_combined[is_inlier], "pred": pred_combined[is_inlier]}
)

# 2. Group into 100-point True Elo brackets
bins = np.arange(400, 3100, 100)
eval_df["true_bracket"] = pd.cut(eval_df["true"], bins=bins, right=False)

# Compute calibration summary statistics per bracket (including 99% interval: 0.5th to 99.5th)
summary = []
for b in eval_df["true_bracket"].cat.categories:
    subset = eval_df[eval_df["true_bracket"] == b]["pred"].dropna()
    if len(subset) < 25:
        continue

    # Added 0.5 and 99.5 for the 99% band
    p005, p05, p25, p50, p75, p95, p995 = np.percentile(
        subset, [0.5, 5, 25, 50, 75, 95, 99.5]
    )
    midpoint = (b.left + b.right) / 2

    summary.append(
        {
            "true_mid": midpoint,
            "pred_median": p50,
            "pred_p005": p005,
            "pred_p05": p05,
            "pred_p25": p25,
            "pred_p75": p75,
            "pred_p95": p95,
            "pred_p995": p995,
            "count": len(subset),
            "label": f"{int(b.left)}–{int(b.right)}",
        }
    )

stats_df = pd.DataFrame(summary)

# 3. Build the Parity Plot
fig = go.Figure()

# A. 99% Confidence Interval Band (0.5th to 99.5th Percentile)
fig.add_trace(
    go.Scatter(
        x=np.concatenate([stats_df["true_mid"], stats_df["true_mid"][::-1]]),
        y=np.concatenate([stats_df["pred_p995"], stats_df["pred_p005"][::-1]]),
        fill="toself",
        fillcolor="rgba(78, 140, 255, 0.08)",  # Very faint outer halo
        line=dict(color="rgba(255,255,255,0)"),
        name="99% Spread (0.5th–99.5th)",
        hoverinfo="skip",
    )
)

# B. 90% Confidence Interval Band (5th to 95th Percentile)
fig.add_trace(
    go.Scatter(
        x=np.concatenate([stats_df["true_mid"], stats_df["true_mid"][::-1]]),
        y=np.concatenate([stats_df["pred_p95"], stats_df["pred_p05"][::-1]]),
        fill="toself",
        fillcolor="rgba(78, 140, 255, 0.18)",
        line=dict(color="rgba(255,255,255,0)"),
        name="90% Spread (5th–95th)",
        hoverinfo="skip",
    )
)

# C. 50% Confidence Interval Band (25th to 75th Percentile / IQR)
fig.add_trace(
    go.Scatter(
        x=np.concatenate([stats_df["true_mid"], stats_df["true_mid"][::-1]]),
        y=np.concatenate([stats_df["pred_p75"], stats_df["pred_p25"][::-1]]),
        fill="toself",
        fillcolor="rgba(78, 140, 255, 0.38)",
        line=dict(color="rgba(255,255,255,0)"),
        name="50% Spread (IQR)",
        hoverinfo="skip",
    )
)

# D. Ideal Identity Line (y = x)
fig.add_trace(
    go.Scatter(
        x=[400, 3000],
        y=[400, 3000],
        mode="lines",
        name="Ideal Parity (y = x)",
        line=dict(color="rgba(255, 255, 255, 0.6)", width=2, dash="dash"),
        hoverinfo="skip",
    )
)

# E. Model Median Response Points
fig.add_trace(
    go.Scatter(
        x=stats_df["true_mid"],
        y=stats_df["pred_median"],
        mode="lines+markers",
        name="Model Median",
        line=dict(color="#4e8cff", width=2.5),
        marker=dict(size=7, color="#ffffff", line=dict(color="#4e8cff", width=2)),
        hovertemplate=(
            "<b>True Elo Bracket: %{customdata[0]}</b><br>"
            + "Median Guess: %{y:.0f}<br>"
            + "50% Spread: [%{customdata[1]:.0f}, %{customdata[2]:.0f}]<br>"
            + "90% Spread: [%{customdata[3]:.0f}, %{customdata[4]:.0f}]<br>"
            + "99% Spread: [%{customdata[5]:.0f}, %{customdata[6]:.0f}]<br>"
            + "Sample Count: %{customdata[7]:,}<extra></extra>"
        ),
        customdata=stats_df[
            [
                "label",
                "pred_p25",
                "pred_p75",
                "pred_p05",
                "pred_p95",
                "pred_p005",
                "pred_p995",
                "count",
            ]
        ],
    )
)

# 4. Layout with 100-Elo tick intervals
fig.update_layout(
    title=dict(
        text="<b>Predicted vs. True Elo</b>",
        font=dict(size=18, color="#ffffff"),
        x=0.04,
        y=0.96,
    ),
    xaxis=dict(
        title="<b>Ground Truth Elo</b>",
        range=[350, 3050],
        dtick=100,
        tickangle=-45,
        gridcolor="#282a2e",
        zeroline=False,
    ),
    yaxis=dict(
        title="<b>Predicted Elo</b>",
        range=[350, 3050],
        dtick=100,
        gridcolor="#282a2e",
        zeroline=False,
    ),
    plot_bgcolor="#18191c",
    paper_bgcolor="#1e1f23",
    font=dict(color="#e0e0e0", family="Inter, sans-serif"),
    width=900,
    height=800,
    margin=dict(l=70, r=40, t=70, b=80),
    legend=dict(
        x=0.04,
        y=0.92,
        bgcolor="rgba(24, 25, 28, 0.85)",
        bordercolor="#3e4046",
        borderwidth=1,
    ),
)

fig.show()

fig.write_image("parity_plot.png", width=900, height=800, scale=3)